swagger: '2.0'

info:
  x-ibm-name: anz_poc_weather_api1
  title: anz_poc_weather_api1
  version: 1.0.0

schemes:
    - https
host: $(catalog.host)
basePath: /v1/anz/poc

consumes:
  - application/json
produces:
  - application/json

x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - proxy:
          title: proxy
          timeout: 60
          verb: keep
          cache-response: protocol
          cache-ttl: 900
          version: 1.0.0
          secure-gateway: false
          target-url: 'https://samples.openweathermap.org/data/2.5/weather'
  gateway: datapower-gateway
paths:
  /weather:
    get:
      responses:
        '200':
          description: 200 OK
definitions: {}
tags: []

