---
swagger: '2.0'

info:
  name: testapi1
  title: testapi1
  version: 1.0.0

schemes:
    - https
host: $(catalog.host)
basePath: /v1/anz/poc

consumes:
  - application/json
produces:
  - application/json
